//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupaShoes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderContents
    {
        public long id { get; set; }
        public long order_id { get; set; }
        public string product_article { get; set; }
        public int count { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Products Products { get; set; }
    }
}
