//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupaShoes.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.OrderContents = new HashSet<OrderContents>();
        }
    
        public string article { get; set; }
        public string name { get; set; }
        public long unit_id { get; set; }
        public decimal price { get; set; }
        public long supplier_id { get; set; }
        public long manufacturer_id { get; set; }
        public long category_id { get; set; }
        public int discount { get; set; }
        public int count { get; set; }
        public string description { get; set; }
        public string image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderContents> OrderContents { get; set; }
        public virtual Partners Partners { get; set; }
        public virtual Partners Partners1 { get; set; }
        public virtual ProductCategories ProductCategories { get; set; }
        public virtual Units Units { get; set; }

        public string Background
        {
            get
            {
                if (this.discount > 15)
                {
                    return "#2E8B57";
                }
                else if (this.count == 0)
                {
                    return "Blue";
                }

                return "#fff";
            }
        }

        public string costLineThrough
        {
            get
            {
                if (this.discount > 0)
                {
                    var cost = $"{this.price: ##}";
                    var costLineThrough = string.Concat(cost.Select(c => c + "\u0336"));
                    return $"{costLineThrough}";
                }
                return null;
            }
        }

        public string costWithDiscount
        {
            get
            {
                if (this.discount > 0)
                {
                    var costWithDiscount = Convert.ToDecimal(this.price) - Convert.ToDecimal(this.price / 100) * Convert.ToDecimal(this.discount);
                    var cost = $"{this.price: ##}";
                    var costLineThrough = string.Concat(cost.Select(c => c + "\u0336"));
                    return $"{costWithDiscount: ##} руб";
                }
                return $"{this.price: ##} руб";
            }
        }

        public string ImgPath
        {
            get
            {
                if (!string.IsNullOrWhiteSpace(this.image))
                    return $"pack://application:,,,/Resources/{this.image}";

                return "pack://application:,,,/Resources/picture.png";
            }
        }
    }
}
